// <auto-generated />
namespace ImperialNova.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Turles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Turles));
        
        string IMigrationMetadata.Id
        {
            get { return "202309251258446_Turles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
